"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
    sudo python setup.py py2app -A
    ./dist/runtime.app/Contents/MacOS/runtime

    python setup.py py2app --optimize 2

"""

#//DON'T FORGET TO:
# boot with CMD-R
# get terminal
# csrutil status
# csrutil enable/disable
# reboot


from setuptools import setup
import os

APP = ['runtime.py']
DATA_FILES = ['runtime-variables.plist',
              'pf_tempesta_seven.ttf',
              'untitled2.obj',
              'untitled2.mtl',
              'untitled-sub.obj',
              'untitled-sub.mtl']

m = [map(lambda y: x[0]+y, x[2]) for x in os.walk('audio/') if x[2][0] != '.']
DATA_FILES.append(('audio', m[0]))

OPTIONS = {'argv_emulation': True,
           'plist': 'Info.plist'}

print DATA_FILES

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app','pygame','gameobjects'],
    version='1.0',
    description='runtime - Space Program X29',
    author='sac'
)
